//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsr1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int SessionID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> TimeLogout { get; set; }
        public Nullable<System.TimeSpan> TimeLogin { get; set; }
        public Nullable<System.TimeSpan> TotalTimeInSystem { get; set; }
        public string FeedBack { get; set; }
        public Nullable<System.TimeSpan> TimeSpentInOneSession { get; set; }
        public Nullable<int> NumberOfCrushes { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
